=== jiang-ruo/xlo-core/src/main/resources/xlo/catcher/catcher.xsd
<?xml version="1.0"?>
<!--targetNamespace需要和xmlns保持一致，且最好使用绝对路径-->
<!--xml中xmlns和xsi:schemaLocation引用上方的值用于寻找xsd文件-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://xlo/xsd/catcher"
		   xmlns:c="http://xlo/xsd/catcher"
		   elementFormDefault="qualified">

	<xs:element name="catcher">
		<xs:complexType>
			<xs:sequence>
<!--				用于全局开启正则表达式，默认为false-->
				<xs:element name="regular" type="xs:boolean" minOccurs="0"/>
				<xs:element ref="c:catch" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
<!--		设置catcher下的catch id唯一-->
		<xs:unique name="catchUnique">
			<xs:selector xpath="c:catch"/>
			<xs:field xpath="@id"/>
		</xs:unique>
	</xs:element>

	<xs:element name="catch">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="c:target" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="id" use="required" type="xs:string"/>
<!--			默认采用全局设置，如果在catch中设置了regular属性，则默认采用此处的设置-->
			<xs:attribute name="regular" type="xs:boolean"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="target">
		<xs:complexType>
<!--	规定target标签仅拥有文本和regular属性-->
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="regular" type="xs:boolean"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== jiang-ruo/xlo-core/src/test/resources/xlo/catcher/catch.xml
<?xml version="1.0"?>
<catcher xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xmlns="http://xlo/xsd/catcher"
		 xsi:schemaLocation="http://xlo/xsd/catcher
		 https://raw.githubusercontent.com/jiang-ruo/xlo-core/main/src/main/resources/xlo/catcher/catcher.xsd">

<!--	未登录的情况下允许访问的页面-->
	<regular>true</regular>
	
	<catch id="pass">
		<target>.*\.xb</target>
		<target>/backstage/login\.jsp</target>
		<target>/backstage/css/.*</target>
		<target>/backstage/fonts/.*</target>
		<target>/backstage/js/.*</target>
		<target>/backstage/lib/.*</target>
		<target>/backstage/imgs/.*</target>
	</catch>

<!--	已经登陆的情况下不允许访问的页面-->
	<catch id="block" regular="false">
		<target>/backstage/.eslintrc.js</target>
	</catch>
</catcher>
